#!/usr/bin/env node
/*
 * Packs the app into one self-contained file:  node tools/build.js  →  Brezel.html
 *  - inlines css/app.css and every <script src> from index.html (same order)
 *  - the result needs no other files, so it opens even where the browser may only
 *    read the file you double-clicked (e.g. macOS privacy protection on Downloads),
 *    and it is easy to copy to a phone.
 * Edit the source files, not Brezel.html — re-run this after adding cards.
 */
'use strict';
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const read = (rel) => fs.readFileSync(path.join(root, rel), 'utf8');
// A literal "</script" or "</style" inside inlined code would end the tag early.
const guard = (code, tag) => code.replace(new RegExp(`</${tag}`, 'gi'), `<\\/${tag}`);

let html = read('index.html');
let scripts = 0;

html = html.replace(/<link\s+rel="stylesheet"\s+href="([^"]+)"\s*\/?>/g, (_, href) => `<style>\n${guard(read(href), 'style')}\n</style>`);
html = html.replace(/<script\s+src="([^"]+)"><\/script>/g, (_, src) => {
  scripts++;
  return `<script>/* ${src} */\n${guard(read(src), 'script')}\n</script>`;
});
html = html.replace('<!doctype html>', '<!doctype html>\n<!-- Generated by tools/build.js from index.html — edit the source files and re-run the build. -->');

const leftover = html.match(/<(?:script|link)\b[^>]*\b(?:src|href)="(?!data:|https?:)[^"]+"/g);
if (leftover) {
  console.error('✗ Some files were not inlined:\n  ' + leftover.join('\n  '));
  process.exit(1);
}

const out = path.join(root, 'Brezel.html');
fs.writeFileSync(out, html);
console.log(`✓ Brezel.html written (${scripts} scripts + styles inlined, ${Math.round(fs.statSync(out).size / 1024)} KB)`);
